name: 'Cloud Run'
description: 'Authenticate with gcloud and deploy as a new revision to Cloud Run'
author: 'jmn <norlund@gmail.com>'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  image:
    description: 'Name of the docker image'
    required: true
  service:
    description: 'Name of the service in Cloud Run'
    required: true
  project:
    description: 'GCP project'
    required: true
  region:
    description: 'GCP region'
    required: true
  service key:
    description: 'GCP service key with storage and run permissions'
    required: true
  env:
    description: 'path to an ENV file'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
